### ISSUE TITLE
marker shadows

### ISSUE THREAD

**Issue by adriennn** [hiasinho/Leaflet.vector-markers#9]
I see you have SVG shadows on your todo list.
What I am doing is using css to create the drop shadows, it's not as pretty as handmade png shadows (which kind of defeat the idea of svg markers ;-) ), but maybe one can tweak the values. This is what I'm doing:

Create the marker

``` javascript

              var myVectorMarkerIcon = L.VectorMarkers.icon({
                prefix: 'fa',
                icon: 'check',
                markerColor: 'lightgray',
            });

```

and then in with css (note that you need to set the style specifically for the full class with the marker color. Note also that this shadow settings is for the default marker):

``` css

.vector-marker-icon-blue:before {
     position: absolute;
     content: "";
     z-index: -1;
     right: 22px;
     bottom: -5px;
     width: 60%;
     height: 30%;         
     box-shadow: 30px -10px 10px rgba(0,0,0,0.4);
 -webkit-transform: skew(150deg);
 -moz-transform: skew(150deg);
  -ms-transform: skew(150deg);
  -o-transform: skew(150deg);
    transform: skew(150deg); 
    -webkit-transform-origin: 50% 50%;
     -moz-transform-origin: 50% 50%;
    -ms-transform-origin: 50% 50%;
    -o-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
 }
}

```

Result:

![shadow](https://cloud.githubusercontent.com/assets/7082644/9836570/20a75188-5a27-11e5-919e-f523081fb817.png)

edit: there might be a way to embellish the shadow by using the drop-shadow filter in css but I haven't trie it yet.
